### ISSUE TITLE
`mdformat.text` and executable yield different results

### ISSUE THREAD

**Issue by twentylemon** [hukkin/mdformat#487]
### Describe the bug

**context**
Our project includes test cases to ensure the formatter for the repo was actually run: [code](https://github.com/duck-dynasty/duckbot/blob/main/tests/fixtures/mdformat/__init__.py#L49-L53). TLDR, it does,
```python
assert file_content == mdformat.text(file_content)
```

However these tests started to fail with 0.7.19. PR is https://github.com/duck-dynasty/duckbot/pull/1019.

Running the formatter once yielded some changes (some double spaces removed), but it didn't change anything else. The tests are failing now though because `mdformat.text` is reformatting tables to remove whitespace in the columns for alignment. Running the formatter script from the console does not change any of the files, and `mdformat --check .` does not error out.

**expectation**
`mdformat.text` and the executable to give the same formatting.

**bug**
`mdformat.text` removes whitespace in tables, which the executable does not.

### Reproduce the bug

(example taken from the failing files in our tests)

```bash
$ printf '|            Command             | Summary                              |
| :----------------------------: | ------------------------------------ |
|            `!8ball`            | get a magic eight ball style fortune |
| [`!yolo`](#yolo-pull-requests) | list open pull requests in this repo |' > file.md

$ mdformat file.md

$ python -c 'import mdformat ; print(mdformat.text("""|            Command             | Summary                              |
| :----------------------------: | ------------------------------------ |
|            `!8ball`            | get a magic eight ball style fortune |
| [`!yolo`](#yolo-pull-requests) | list open pull requests in this repo |"""))'
```

`cat file.md` yields,
```
|            Command             | Summary                              |
| :----------------------------: | ------------------------------------ |
|            `!8ball`            | get a magic eight ball style fortune |
| [`!yolo`](#yolo-pull-requests) | list open pull requests in this repo |
```

python output is
```
| Command | Summary |
| :----------------------------: | ------------------------------------ |
| `!8ball` | get a magic eight ball style fortune |
| [`!yolo`](#yolo-pull-requests) | list open pull requests in this repo |
```

### List your environment

```
$ mdformat --version
mdformat 0.7.19 (mdformat_tables 1.0.0, mdformat-gfm 0.3.7, mdformat-black 0.1.1)
```

**Comment by hukkin** [comment]
Please see https://mdformat.readthedocs.io/en/stable/users/plugins.html#parser-extension-plugins
> For stability, mdformat Python API behavior will not change simply due to a plugin being installed. Extensions will have to be explicitly enabled in addition to being installed:

So the difference between CLI and API output is explained by plugins being enabled on the CLI by default which does not happen with Python API.

**Comment by twentylemon** [comment]
Odd! Is that new behaviour? These tests are ~2 years old!

Thanks though, I will make the change on my end.

**Comment by hukkin** [comment]
The behavior has always been that way. What's new is that mdformat reduces whitespace sequences to one space. If you have `mdformat-tables` it won't (and would not) do that in tables.

Closing as resolved.
